---
inv_secret_tech_user_public_ssh_key: >-
  {{
    lookup('community.hashi_vault.vault_kv2_get',
      'auth/gitlab.com',
      engine_mount_point='dev.rachuna')['secret']['public_ssh_key']
  }}

inv_secret_tech_user_private_ssh_key: >-
  {{
    lookup('community.hashi_vault.vault_kv2_get',
    'auth/gitlab.com',
    engine_mount_point='dev.rachuna')['secret']['private_ssh_key']
  }}

inv_secret_mrachuna_public_ssh_key: >-
  {{ lookup('community.hashi_vault.vault_kv2_get',
    'mrachuna/ssh',
    engine_mount_point='users')['secret']['PUBLIC_KEY']
  }}

inv_secret_dragoslawai_public_ssh_key: >-
  {{ lookup('community.hashi_vault.vault_kv2_get',
    'dragoslawai/ssh',
    engine_mount_point='users')['secret']['PUBLIC_KEY']
  }}

inv_secret_keepalived_auth_pass: >
  {{
    lookup('community.hashi_vault.vault_kv2_get',
    'infrastructure/vault-rachuna-dev/ansible',
    engine_mount_point='dev.rachuna')['secret']['vip_authentication_pass']
  }}

inv_secret_unseal_keys_1: >-
  {{
    lookup('community.hashi_vault.vault_kv2_get',
    'infrastructure/vault-rachuna-dev/ansible',
    engine_mount_point='dev.rachuna')['secret']['VAULT_UNSEAL_KEY_1']
  }}
